report test errors

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -126,14 +126,24 @@ jobs:
       - name: Run Integration Tests
         run: ./gradlew integrationTest
 
+      - uses: actions/upload-artifact@v4  # upload test results
+        if: success() || failure()        # run this step even if previous step failed
+        with:
+          name: test-results-integration
+          path: build/reports/tests/integrationTest/index.html
+
   # Combine test reports if needed
   test-report:
     name: Test Report
     runs-on: ubuntu-latest
     needs: [unit-test, integration-test]
     steps:
-      - name: Generate Test Report
-        run: echo "Combine and process test reports here"
+      - uses: dorny/test-reporter@v1
+        with:
+          artifact: /test-results-(.*)/            # artifact name
+          name: java-junit               # Name of the check run which will be created
+          path: '*.html'                     # Path to test results (inside artifact .zip)
+          reporter: jest-junit              # Format of test results
 
   push-dockerhub-native-main-amd64:
     name: Push Native Image (AMD64)
